export interface Product {
  id: number;
  rank: number;
  name: string;
  badge: string;
  badgeColor: "primary" | "accent" | "cta";
  image: string;
  specs: string[];
  verdict: string;
  pros: string[];
  cons: string[];
  amazonUrl: string;
  mlUrl: string;
  reviewUrl: string;
}

export const products: Product[] = [
  {
    id: 1,
    rank: 1,
    name: "Samsung SHP-DP609",
    badge: "Melhor do Ano",
    badgeColor: "accent",
    image: "/images/products/samsung-dp609.jpg",
    specs: ["Biometria 3D", "Wi-Fi integrado", "Abertura por app", "IP65"],
    verdict:
      "A Samsung SHP-DP609 lidera nosso ranking por combinar tecnologia de ponta com confiabilidade. O sensor biométrico 3D reconhece impressões digitais em menos de 0,3s.",
    pros: [
      "Sensor 3D ultrarrápido",
      "Integração com assistentes virtuais",
      "Design premium",
      "Alta durabilidade",
    ],
    cons: ["Preço elevado", "Instalação requer profissional"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/samsung-shp-dp609",
  },
  {
    id: 2,
    rank: 2,
    name: "Yale YMF 40",
    badge: "Mais Vendida",
    badgeColor: "primary",
    image: "/images/products/yale-ymf40.jpg",
    specs: [
      "Biometria capacitiva",
      "Senha numérica",
      "Cartão RFID",
      "Auto-travamento",
    ],
    verdict:
      "A Yale YMF 40 é referência no mercado brasileiro. Confiável, robusta e com excelente acabamento, ideal para quem busca segurança comprovada.",
    pros: [
      "Marca reconhecida",
      "Fácil instalação",
      "Múltiplas formas de abertura",
      "Boa autonomia de bateria",
    ],
    cons: ["Sem Wi-Fi nativo", "Design conservador"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/yale-ymf-40",
  },
  {
    id: 3,
    rank: 3,
    name: "Intelbras FR 220",
    badge: "Melhor Custo-Benefício",
    badgeColor: "cta",
    image: "/images/products/intelbras-fr220.jpg",
    specs: ["Biometria óptica", "Senha", "Cartão", "Até 100 digitais"],
    verdict:
      "A Intelbras FR 220 oferece um conjunto excelente de funcionalidades por um preço acessível. Ideal para quem está migrando de fechaduras mecânicas.",
    pros: [
      "Preço competitivo",
      "Marca nacional com bom suporte",
      "Instalação simples",
      "Silenciosa",
    ],
    cons: ["Sensor óptico mais lento", "Sem conectividade app"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/intelbras-fr-220",
  },
  {
    id: 4,
    rank: 4,
    name: "Philips EasyKey 9300",
    badge: "Mais Tecnológica",
    badgeColor: "primary",
    image: "/images/products/philips-easykey-9300.jpg",
    specs: [
      "Reconhecimento facial 3D",
      "Biometria",
      "Wi-Fi",
      "Câmera integrada",
    ],
    verdict:
      "A Philips EasyKey 9300 traz reconhecimento facial 3D e câmera integrada, representando o futuro das fechaduras inteligentes no Brasil.",
    pros: [
      "Reconhecimento facial preciso",
      "Câmera com visão noturna",
      "App completo",
      "Design futurista",
    ],
    cons: ["Preço premium", "Consumo de bateria maior"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/philips-easykey-9300",
  },
  {
    id: 5,
    rank: 5,
    name: "Papaiz Smart Lock Wi-Fi",
    badge: "Melhor Wi-Fi",
    badgeColor: "primary",
    image: "/images/products/papaiz-smart-wifi.jpg",
    specs: ["Wi-Fi nativo", "Biometria", "Senha", "Alexa e Google"],
    verdict:
      "A Papaiz Smart Lock Wi-Fi se destaca pela integração perfeita com ecossistemas de casa inteligente, permitindo controle total pelo celular.",
    pros: [
      "Wi-Fi sem bridge",
      "Compatível com Alexa/Google",
      "Histórico de acessos",
      "Marca tradicional",
    ],
    cons: ["Biometria pode falhar com dedos molhados", "Wi-Fi 2.4GHz apenas"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/papaiz-smart-wifi",
  },
  {
    id: 6,
    rank: 6,
    name: "Multilaser SE232",
    badge: "Compacta",
    badgeColor: "primary",
    image: "/images/products/multilaser-se232.jpg",
    specs: ["Biometria", "Senha", "Chave mecânica", "Design slim"],
    verdict:
      "A Multilaser SE232 é perfeita para portas de apartamento, com design compacto e funcionalidades essenciais a um preço justo.",
    pros: [
      "Design fino e discreto",
      "Preço acessível",
      "Fácil instalação DIY",
      "Leve",
    ],
    cons: ["Poucas funções avançadas", "Sem conectividade"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/multilaser-se232",
  },
  {
    id: 7,
    rank: 7,
    name: "Kaba Penta Digi",
    badge: "Mais Robusta",
    badgeColor: "primary",
    image: "/images/products/kaba-penta.jpg",
    specs: ["Biometria", "IP66", "Senha", "Chave de emergência"],
    verdict:
      "Projetada para ambientes hostis, a Kaba Penta Digi é a mais resistente da lista, com certificação IP66 contra água e poeira.",
    pros: [
      "Extremamente resistente",
      "IP66 certificado",
      "Construção sólida",
      "Ideal para áreas externas",
    ],
    cons: ["Design industrial", "Sem Wi-Fi", "Preço elevado"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/kaba-penta-digi",
  },
  {
    id: 8,
    rank: 8,
    name: "Lockwell LW500",
    badge: "Boa Autonomia",
    badgeColor: "primary",
    image: "/images/products/lockwell-lw500.jpg",
    specs: [
      "Biometria",
      "12 meses de bateria",
      "Senha",
      "Alarme anti-arrombamento",
    ],
    verdict:
      "Com até 12 meses de autonomia, a Lockwell LW500 é ideal para quem não quer se preocupar com troca frequente de pilhas.",
    pros: [
      "Bateria de longa duração",
      "Alarme integrado",
      "Custo justo",
      "Silenciosa",
    ],
    cons: ["Marca menos conhecida", "Sem app"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/lockwell-lw500",
  },
  {
    id: 9,
    rank: 9,
    name: "Control iD iDFlex Pro",
    badge: "Uso Comercial",
    badgeColor: "primary",
    image: "/images/products/controlid-idflex.jpg",
    specs: [
      "Biometria + RFID",
      "Software de gestão",
      "Até 10.000 usuários",
      "PoE",
    ],
    verdict:
      "A Control iD iDFlex Pro é a melhor escolha para empresas e condomínios que precisam de controle de acesso profissional.",
    pros: [
      "Capacidade massiva de usuários",
      "Software de gestão incluso",
      "Alta velocidade de leitura",
      "Conectividade PoE",
    ],
    cons: ["Não ideal para residências", "Requer infraestrutura de rede"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/controlid-idflex-pro",
  },
  {
    id: 10,
    rank: 10,
    name: "Positivo Smart Fechadura",
    badge: "Casa Inteligente",
    badgeColor: "primary",
    image: "/images/products/positivo-smart.jpg",
    specs: ["Wi-Fi", "Biometria", "NFC", "Compatível com Positivo Casa"],
    verdict:
      "Para quem já usa o ecossistema Positivo Casa Inteligente, esta fechadura se integra perfeitamente com os demais dispositivos da marca.",
    pros: [
      "Integração com ecossistema Positivo",
      "NFC para celular",
      "App intuitivo",
      "Preço competitivo",
    ],
    cons: ["Melhor em ecossistema Positivo", "Biometria mediana"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/positivo-smart",
  },
  {
    id: 11,
    rank: 11,
    name: "Commax CDL-S210",
    badge: "Design Elegante",
    badgeColor: "primary",
    image: "/images/products/commax-cdl.jpg",
    specs: ["Senha touch", "Cartão RFID", "Auto-lock", "Design minimalista"],
    verdict:
      "A Commax CDL-S210 conquista pelo visual sofisticado e painel touch responsivo. Ótima para ambientes modernos que valorizam estética.",
    pros: [
      "Design premium",
      "Painel touch sensível",
      "Silenciosa",
      "Bom custo",
    ],
    cons: ["Sem biometria", "Sem Wi-Fi"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/commax-cdl-s210",
  },
  {
    id: 12,
    rank: 12,
    name: "Garen Smartlock Pro",
    badge: "Nacional",
    badgeColor: "primary",
    image: "/images/products/garen-smartlock.jpg",
    specs: ["Biometria", "Senha", "App Bluetooth", "Alarme"],
    verdict:
      "A Garen Smartlock Pro é uma opção nacional que oferece Bluetooth para controle via app e um sensor biométrico eficiente.",
    pros: [
      "Fabricação nacional",
      "Bom suporte técnico",
      "Bluetooth funcional",
      "Custo acessível",
    ],
    cons: ["Sem Wi-Fi", "App pode melhorar"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/garen-smartlock-pro",
  },
  {
    id: 13,
    rank: 13,
    name: "Dessmann Q7FP",
    badge: "Importado Premium",
    badgeColor: "primary",
    image: "/images/products/dessmann-q7fp.jpg",
    specs: ["Push-pull", "Biometria semicondutora", "Senha", "Cartão"],
    verdict:
      "A Dessmann Q7FP impressiona pelo mecanismo push-pull e sensor biométrico semicondutor de alta precisão.",
    pros: [
      "Mecanismo push-pull inovador",
      "Sensor de alta precisão",
      "Construção sólida",
      "Design diferenciado",
    ],
    cons: ["Importação pode ser difícil", "Garantia limitada no Brasil"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/dessmann-q7fp",
  },
  {
    id: 14,
    rank: 14,
    name: "HDL C-90 Digital",
    badge: "Básica Confiável",
    badgeColor: "primary",
    image: "/images/products/hdl-c90.jpg",
    specs: ["Senha", "Cartão RFID", "Chave mecânica", "Anti-pânico"],
    verdict:
      "A HDL C-90 Digital é uma opção básica e confiável para quem quer apenas substituir a fechadura mecânica por um modelo digital simples.",
    pros: [
      "Muito acessível",
      "Marca conhecida",
      "Instalação fácil",
      "Função anti-pânico",
    ],
    cons: ["Sem biometria", "Funcionalidades limitadas"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/hdl-c90",
  },
  {
    id: 15,
    rank: 15,
    name: "Milre MI-6800",
    badge: "Tecnologia Coreana",
    badgeColor: "primary",
    image: "/images/products/milre-mi6800.jpg",
    specs: ["Biometria", "Senha", "Cartão", "Teclado iluminado"],
    verdict:
      "A Milre MI-6800 traz a confiabilidade da tecnologia coreana com um sensor biométrico rápido e teclado retroiluminado.",
    pros: [
      "Tecnologia coreana confiável",
      "Sensor rápido",
      "Teclado iluminado",
      "Boa durabilidade",
    ],
    cons: ["Pouca presença no mercado BR", "Manual em inglês"],
    amazonUrl: "#",
    mlUrl: "#",
    reviewUrl: "/review/milre-mi6800",
  },
];
