fragment ReviewsParts on Reviews {
  __typename
  title
  description
  date
  featured
  tags
  seoTitle
  seoDescription
  pros
  cons
  affiliateLink
  mlLink
  priceText
  highlight
  rating
  images {
    __typename
    url
    alt
  }
  body
}

fragment ComparativosParts on Comparativos {
  __typename
  title
  description
  date
  featured
  tags
  seoTitle
  seoDescription
  products {
    __typename
    position
    title
    image
    extraImages {
      __typename
      url
    }
    badge
    rating
    reviewCount
    amazonLink
    mercadoLivreLink
  }
  body
}

fragment GuiasParts on Guias {
  __typename
  title
  description
  date
  featured
  tags
  seoTitle
  seoDescription
  products {
    __typename
    position
    title
    image
    extraImages {
      __typename
      url
    }
    badge
    rating
    reviewCount
    amazonLink
    mercadoLivreLink
  }
  body
}
