//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  reviews: Reviews;
  reviewsConnection: ReviewsConnection;
  comparativos: Comparativos;
  comparativosConnection: ComparativosConnection;
  guias: Guias;
  guiasConnection: GuiasConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
};


export type QueryComparativosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryComparativosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ComparativosFilter>;
};


export type QueryGuiasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGuiasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuiasFilter>;
};

export type DocumentFilter = {
  reviews?: InputMaybe<ReviewsFilter>;
  comparativos?: InputMaybe<ComparativosFilter>;
  guias?: InputMaybe<GuiasFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Reviews | Comparativos | Guias | Folder;

export type Reviews = Node & Document & {
  __typename?: 'Reviews';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  pros?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  cons?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  affiliateLink?: Maybe<Scalars['String']['output']>;
  priceText?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ReviewsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  type?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  tags?: InputMaybe<StringFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  pros?: InputMaybe<StringFilter>;
  cons?: InputMaybe<StringFilter>;
  affiliateLink?: InputMaybe<StringFilter>;
  priceText?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ReviewsConnectionEdges = {
  __typename?: 'ReviewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Reviews>;
};

export type ReviewsConnection = Connection & {
  __typename?: 'ReviewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReviewsConnectionEdges>>>;
};

export type Comparativos = Node & Document & {
  __typename?: 'Comparativos';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  affiliateLink?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ComparativosFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  type?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  tags?: InputMaybe<StringFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  affiliateLink?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ComparativosConnectionEdges = {
  __typename?: 'ComparativosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Comparativos>;
};

export type ComparativosConnection = Connection & {
  __typename?: 'ComparativosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ComparativosConnectionEdges>>>;
};

export type Guias = Node & Document & {
  __typename?: 'Guias';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GuiasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  type?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  tags?: InputMaybe<StringFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type GuiasConnectionEdges = {
  __typename?: 'GuiasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Guias>;
};

export type GuiasConnection = Connection & {
  __typename?: 'GuiasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GuiasConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateReviews: Reviews;
  createReviews: Reviews;
  updateComparativos: Comparativos;
  createComparativos: Comparativos;
  updateGuias: Guias;
  createGuias: Guias;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationCreateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationUpdateComparativosArgs = {
  relativePath: Scalars['String']['input'];
  params: ComparativosMutation;
};


export type MutationCreateComparativosArgs = {
  relativePath: Scalars['String']['input'];
  params: ComparativosMutation;
};


export type MutationUpdateGuiasArgs = {
  relativePath: Scalars['String']['input'];
  params: GuiasMutation;
};


export type MutationCreateGuiasArgs = {
  relativePath: Scalars['String']['input'];
  params: GuiasMutation;
};

export type DocumentUpdateMutation = {
  reviews?: InputMaybe<ReviewsMutation>;
  comparativos?: InputMaybe<ComparativosMutation>;
  guias?: InputMaybe<GuiasMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  reviews?: InputMaybe<ReviewsMutation>;
  comparativos?: InputMaybe<ComparativosMutation>;
  guias?: InputMaybe<GuiasMutation>;
};

export type ReviewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  pros?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cons?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  affiliateLink?: InputMaybe<Scalars['String']['input']>;
  priceText?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ComparativosMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  affiliateLink?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GuiasMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ReviewsPartsFragment = { __typename: 'Reviews', title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, pros?: Array<string | null> | null, cons?: Array<string | null> | null, affiliateLink?: string | null, priceText?: string | null, highlight?: string | null, body?: any | null };

export type ComparativosPartsFragment = { __typename: 'Comparativos', title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, affiliateLink?: string | null, body?: any | null };

export type GuiasPartsFragment = { __typename: 'Guias', title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null };

export type ReviewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReviewsQuery = { __typename?: 'Query', reviews: { __typename: 'Reviews', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, pros?: Array<string | null> | null, cons?: Array<string | null> | null, affiliateLink?: string | null, priceText?: string | null, highlight?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReviewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
}>;


export type ReviewsConnectionQuery = { __typename?: 'Query', reviewsConnection: { __typename?: 'ReviewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReviewsConnectionEdges', cursor: string, node?: { __typename: 'Reviews', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, pros?: Array<string | null> | null, cons?: Array<string | null> | null, affiliateLink?: string | null, priceText?: string | null, highlight?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ComparativosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ComparativosQuery = { __typename?: 'Query', comparativos: { __typename: 'Comparativos', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, affiliateLink?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ComparativosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ComparativosFilter>;
}>;


export type ComparativosConnectionQuery = { __typename?: 'Query', comparativosConnection: { __typename?: 'ComparativosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ComparativosConnectionEdges', cursor: string, node?: { __typename: 'Comparativos', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, affiliateLink?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GuiasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GuiasQuery = { __typename?: 'Query', guias: { __typename: 'Guias', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GuiasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuiasFilter>;
}>;


export type GuiasConnectionQuery = { __typename?: 'Query', guiasConnection: { __typename?: 'GuiasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GuiasConnectionEdges', cursor: string, node?: { __typename: 'Guias', id: string, title: string, description: string, date?: string | null, type: string, featured?: boolean | null, tags?: Array<string | null> | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ReviewsPartsFragmentDoc = gql`
    fragment ReviewsParts on Reviews {
  __typename
  title
  description
  date
  type
  featured
  tags
  seoTitle
  seoDescription
  pros
  cons
  affiliateLink
  priceText
  highlight
  body
}
    `;
export const ComparativosPartsFragmentDoc = gql`
    fragment ComparativosParts on Comparativos {
  __typename
  title
  description
  date
  type
  featured
  tags
  seoTitle
  seoDescription
  affiliateLink
  body
}
    `;
export const GuiasPartsFragmentDoc = gql`
    fragment GuiasParts on Guias {
  __typename
  title
  description
  date
  type
  featured
  tags
  seoTitle
  seoDescription
  body
}
    `;
export const ReviewsDocument = gql`
    query reviews($relativePath: String!) {
  reviews(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReviewsParts
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const ReviewsConnectionDocument = gql`
    query reviewsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReviewsFilter) {
  reviewsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReviewsParts
      }
    }
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const ComparativosDocument = gql`
    query comparativos($relativePath: String!) {
  comparativos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ComparativosParts
  }
}
    ${ComparativosPartsFragmentDoc}`;
export const ComparativosConnectionDocument = gql`
    query comparativosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ComparativosFilter) {
  comparativosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ComparativosParts
      }
    }
  }
}
    ${ComparativosPartsFragmentDoc}`;
export const GuiasDocument = gql`
    query guias($relativePath: String!) {
  guias(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GuiasParts
  }
}
    ${GuiasPartsFragmentDoc}`;
export const GuiasConnectionDocument = gql`
    query guiasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GuiasFilter) {
  guiasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GuiasParts
      }
    }
  }
}
    ${GuiasPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      reviews(variables: ReviewsQueryVariables, options?: C): Promise<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}> {
        return requester<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}, ReviewsQueryVariables>(ReviewsDocument, variables, options);
      },
    reviewsConnection(variables?: ReviewsConnectionQueryVariables, options?: C): Promise<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}> {
        return requester<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}, ReviewsConnectionQueryVariables>(ReviewsConnectionDocument, variables, options);
      },
    comparativos(variables: ComparativosQueryVariables, options?: C): Promise<{data: ComparativosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComparativosQueryVariables, query: string}> {
        return requester<{data: ComparativosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComparativosQueryVariables, query: string}, ComparativosQueryVariables>(ComparativosDocument, variables, options);
      },
    comparativosConnection(variables?: ComparativosConnectionQueryVariables, options?: C): Promise<{data: ComparativosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComparativosConnectionQueryVariables, query: string}> {
        return requester<{data: ComparativosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComparativosConnectionQueryVariables, query: string}, ComparativosConnectionQueryVariables>(ComparativosConnectionDocument, variables, options);
      },
    guias(variables: GuiasQueryVariables, options?: C): Promise<{data: GuiasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuiasQueryVariables, query: string}> {
        return requester<{data: GuiasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuiasQueryVariables, query: string}, GuiasQueryVariables>(GuiasDocument, variables, options);
      },
    guiasConnection(variables?: GuiasConnectionQueryVariables, options?: C): Promise<{data: GuiasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuiasConnectionQueryVariables, query: string}> {
        return requester<{data: GuiasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuiasConnectionQueryVariables, query: string}, GuiasConnectionQueryVariables>(GuiasConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  